// Code generated by MockGen. DO NOT EDIT.
// Source: internal/balancer/mock/mock_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	protos "github.com/r-mol/balanser_highload_system/protos"
)

// MockKeyValueServiceClient is a mock of KeyValueServiceClient interface.
type MockKeyValueServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockKeyValueServiceClientMockRecorder
}

// MockKeyValueServiceClientMockRecorder is the mock recorder for MockKeyValueServiceClient.
type MockKeyValueServiceClientMockRecorder struct {
	mock *MockKeyValueServiceClient
}

// NewMockKeyValueServiceClient creates a new mock instance.
func NewMockKeyValueServiceClient(ctrl *gomock.Controller) *MockKeyValueServiceClient {
	mock := &MockKeyValueServiceClient{ctrl: ctrl}
	mock.recorder = &MockKeyValueServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyValueServiceClient) EXPECT() *MockKeyValueServiceClientMockRecorder {
	return m.recorder
}

// GetValue mocks base method.
func (m *MockKeyValueServiceClient) GetValue(request protos.GetValueRequest) (*protos.GetValueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", request)
	ret0, _ := ret[0].(*protos.GetValueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValue indicates an expected call of GetValue.
func (mr *MockKeyValueServiceClientMockRecorder) GetValue(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockKeyValueServiceClient)(nil).GetValue), request)
}

// New mocks base method.
func (m *MockKeyValueServiceClient) New() (*KeyValueServiceClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(*KeyValueServiceClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockKeyValueServiceClientMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockKeyValueServiceClient)(nil).New))
}

// StoreValue mocks base method.
func (m *MockKeyValueServiceClient) StoreValue(request protos.StoreValueRequest) (*protos.StoreValueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreValue", request)
	ret0, _ := ret[0].(*protos.StoreValueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreValue indicates an expected call of StoreValue.
func (mr *MockKeyValueServiceClientMockRecorder) StoreValue(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreValue", reflect.TypeOf((*MockKeyValueServiceClient)(nil).StoreValue), request)
}
